# .theme-check.yml
# Minimal config for a non-theme repo. Parser errors still fail the run.
ignore:
  - MissingRequiredTemplateFiles
  - RequiredDirectories
  - DefaultLocale
  - ValidJson   # keep ignored to avoid node_modules JSON noisex