# Minimal config. Parser errors (e.g., LiquidHTMLSyntaxError) are errors by default.
ignore: []               # don’t ignore specific checks
include_categories: []   # run the default set of checks
exclude_patterns:
  - node_modules/**      # don’t scan deps
  - .vercel/**           # optional: CI output
  - **/dist/**           # optional: build artifacts
  - **/build/**          # optional: build artifacts