name: Theme Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install theme-check
        run: gem install theme-check

      - name: Run theme-check (fail on errors)
        run: theme-check --fail-level error .